version: '3'
services:
  database: 
    image:  mysql:5.7
    volumes:
      - ./database.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: portal_development
    ports:
      - 3306

  service.config:
    build:
      context: ./service.config/.
      dockerfile: dev.dockerfile
    volumes:
      - ./service.config/.:/usr/src/app/
    ports:
      - 7000:5000
    environment:
      PORT: 5000
    command: python3 main.py
    
  service.session:
    build:
      context: ./service.session/.
      dockerfile: dev.dockerfile
    volumes:
      - ./service.session/.:/usr/src/app/
    ports:
      - 7001:5001 
    depends_on:
      - database
      - service.config
    environment:
      NODE_ENV: development
      PORT: 5001
      GRAPHIQL: 1
    command: npm start 