version: '3'
services:
  module.conteudo:
    build: 
      dockerfile: ./service.conteudo/dev.dockerfile
      context: .
    volumes:
      - ./module.conteudo:/usr/src/module.conteudo
    ports:
      - 7001:5000
    environment:
      NODE_ENV: development
    env_file:
