version: '3'
services:
  # database: 
  #   image:  mysql
  #   volumes:
  #     - ./database.data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: root
  #     MYSQL_DATABASE: portal_development
  #   ports:
  #     - 3334:3306

  service.config:
    build:
      context: ./service.config
      dockerfile: dev.dockerfile
    volumes:
      - ./service.config:/usr/src/app/
    ports:
      - ${EXPOSE_CONFIG_PORT}:${DOCKER_CONFIG_PORT}
    environment:
      PORT: ${DOCKER_CONFIG_PORT}
    command: python main.py
    
  service.session:
    build:
      context: ./service.session
      dockerfile: dev.dockerfile
    volumes:
      - ./service.session:/usr/src/app/
    ports:
      - ${EXPOSE_SESSION_PORT}:${DOCKER_SESSION_PORT}
    depends_on:  
      # - database
      - service.config
    environment:
      NODE_ENV: development
      PORT: ${DOCKER_SESSION_PORT}
      GRAPHIQL: 1
    command: npm start 